### ISSUE TITLE
Windows: Project cannot delete generated JAR file

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1682]
I've noticed that sometimes Bndtools under windows can no longer delete the JAR file that it generates. This seems to happen without another process using this file. (Verified with a utility but that reported nobody was using the file, not even eclipse.)

I guess we should at least report an error when the file cannot be deleted?

**Comment by bjhargrave** [comment]
I have updated Bnd, https://github.com/bndtools/bnd/commit/4cc6f371e4e9facf327e0b9ee77e4b7a27b948b9#diff-36dfafab267cc44e1c2060c59683808eL1807, to throw an exception if a prior version of the jar file cannot be deleted when the Project is built.

I also updated Bndtools, 339146b2bea140303cf5a9ba3d89a88e15abcbe3 and 4f6c810bdd1b4575bacb79d9d02445120c9500ea, to attempt to close some places where Jar objects might not be closed.

**Comment by rherrmann** [comment]
With Bndtools 3.4.0.DEV-20170502-134658 I see errors during build that seem to be related to this issue. 

The English translation of the message is along the lines of 'Cannot delete file because it is used by another process'. It seems that there are still some files left open.

```
org.eclipse.core.runtime.CoreException: Build Error!
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:286)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.nio.file.FileSystemException: C:\Users\Ruediger\git\repo\project\generated\xyz.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at aQute.lib.io.IO$2.visitFile(IO.java:701)
	at aQute.lib.io.IO$2.visitFile(IO.java:694)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at aQute.lib.io.IO.deleteWithException(IO.java:694)
	at aQute.lib.io.IO.deleteWithException(IO.java:675)
	at aQute.bnd.build.Project.saveBuild(Project.java:1803)
	at aQute.bnd.build.Project.buildLocal(Project.java:1743)
	at aQute.bnd.build.Project.build(Project.java:1546)
	at aQute.bnd.build.Project.build(Project.java:2070)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:264)
	at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:127)
	at bndtools.central.Central.bndCall(Central.java:596)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:127)
	... 12 more
```

**Comment by bjhargrave** [comment]
We changed Bnd to throw an exception in `aQute.bnd.build.Project.saveBuild` if the prior version of the jar file cannot be deleted before saving the new version. So some part of Bndtools is holding the file open. Not sure how to figure out which code is not closing the file.

**Comment by rherrmann** [comment]
> Not sure how to figure out which code is not closing the file.

I usually start with inspecting the call hierarchy of `InputStream`, IFile::getContents`, `getResourceAsStream` and the like to see if a caller does not (reliably) close the obtained resource. A tedious approach, but quite often successful.

**Comment by seanbright** [comment]
Is there a public workspace where this is relatively easily to reproduce?

**Comment by rherrmann** [comment]
@seanbright I am afraid, as far as I am concerned, I can't provide one. The issue seems to surface mostly in larger workspaces and besides that, I am currently working on a closed source project.

**Comment by seanbright** [comment]
@rherrmann and there are no specific actions you are taking before this exception occurs? You're just saving a .java file and it happens? Is the JAR viewer open? Is a framework running?

**Comment by rherrmann** [comment]
@seanbright Seems it needs more than just saving a file. I see this issue after working for a while, where working is usually a cycle of saving java files, running tests, and again, saving java files, ... The Jar viewer is not open and no framework is running either.

**Comment by seanbright** [comment]
So I've run a bunch of tests with YourKit to try and determine if we are leaving files open, and it doesn't appear that we are - at least with the tests I am running. My assumption is that we have the file open for one reason or another, and the builder wants to replace it but it cannot. So I don't think we're leaking file handles, I think this is just an unfortunate timing problem. Stay tuned.

**Comment by bjhargrave** [comment]
Thanks for continuing to look at this (since you are our Windows guy).

I went through the code and only found a few possible places we failed to close the jar files and I fixed them. I am wondering if perhaps there is some other Eclipse plugin (not in your Eclipse install) that could be at fault?

**Comment by seanbright** [comment]
I actually saw this exception yesterday afternoon and all I have is Bndtools installed on a fresh Eclipse install. I noticed it after the fact so I'm not sure what I was doing when it occurred.

**Comment by rherrmann** [comment]
Two weeks or so ago I switched from 3.3 to 3.4.DEV and since then noticed this issue more often than before. This may also be coincidence, though. I am still not able to provide the exact steps that lead to this problem. Will report here if I have better details.

**Comment by seanbright** [comment]
We didn't start throwing an exception in this situation until after 3.3 was released. It was happening, you just weren't being notified of it.

**Comment by rherrmann** [comment]
This issue still exists with Bndtools 3.4.0.DEV-20170619

**Comment by bjhargrave** [comment]
But we have do not have enough details to understand the code which is not releasing the file. So I am unsure how to fix this.

**Comment by rherrmann** [comment]
I do understand the difficulties and also tried to have YourKit monitor the Eclipse instance in question, so far without a clue.
Peter asked me this morning to reconfirm that this issue is still there.

**Comment by bjhargrave** [comment]
Are you also using the gradle build? It may be that the gradle daemon is holding jar files open. See https://github.com/gradle/gradle/issues/937

Since the jar files built by one project are classpath entries for the compile task of another project, the gradle daemon's compiler support may be holding the classpath files open. 

Try disabling the gradle daemon to see if that fixes things.

**Comment by rherrmann** [comment]
I don't have the gradle daemon running. Note, that @seanbright could also reproduce the issue with _Bndtools installed on a fresh Eclipse install_.

**Comment by pkriens** [comment]
I've done some more analysing. So far I cannot find any problem with bnd(tools) but I've found 2 suspects: 

* JDT Source Indexer – There is a bug on this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=406170. In a trace I made with Jörn I found exactly this problem. There were hundreds of open files from exactly this bug. They seem to have (partially) fixed this bug in https://github.com/eclipse/eclipse.jdt.core/commit/1c9be7804c5f24d8d2857bf04bda58d61ad462eb but this is in Photon. We probably should ask them to back patch this in Neon.
* Groovy-Eclipse – The other place where a reference was held to the most problematic file was in the Groovy Compilation Unit. The Groovy Compilation unit opened a class loader on the JAR but seemed not to close it. This is further investigated.

      #152 D:\projects\iguana_ld\de.sma.iguana.framework\de.sma.api\generated\de.sma.api.jar by thread:Worker-54 on Thu Sep 28 08:48:57 CEST 2017
        at java.util.zip.ZipFile.<init>(ZipFile.java:150)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:893)
        at sun.misc.URLClassPath$JarLoader.access$700(URLClassPath.java:756)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:838)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:831)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:830)
        at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:803)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:530)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:520)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:519)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:492)
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:457)
        at sun.misc.URLClassPath.access$100(URLClassPath.java:64)
        at sun.misc.URLClassPath$1.next(URLClassPath.java:239)
        at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:250)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:601)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:599)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader$3.next(URLClassLoader.java:598)
        at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:623)
        at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
        at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
        at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
        at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.doAddGlobalTransforms(ASTTransformationVisitor.java:240)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.addGlobalTransforms(ASTTransformationVisitor.java:228)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.addPhaseOperations(ASTTransformationVisitor.java:191)
        at org.codehaus.groovy.control.CompilationUnit.<init>(CompilationUnit.java:222)
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser.makeCompilationUnit(GroovyParser.java:514)
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser.<init>(GroovyParser.java:260)
        at org.codehaus.jdt.groovy.integration.internal.MultiplexingSourceElementRequestorParser.<init>(MultiplexingSourceElementRequestorParser.java:69)
        at org.codehaus.jdt.groovy.model.GroovyCompilationUnit.buildStructure(GroovyCompilationUnit.java:263)
        at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:259)
        at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:583)
        at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:317)
        at org.eclipse.jdt.internal.core.Openable.open(Openable.java:433)
        at org.eclipse.jdt.internal.core.CompilationUnit.getImports(CompilationUnit.java:786)
        at org.bndtools.builder.ComponentMarker.isComponentInImports(ComponentMarker.java:174)
        at org.bndtools.builder.ComponentMarker.parseChildrenForComponents(ComponentMarker.java:110)
        at org.bndtools.builder.ComponentMarker.updateComponentMarkers(ComponentMarker.java:81)
        at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:274)
        at org.bndtools.builder.BndtoolsBuilder$1.call(BndtoolsBuilder.java:127)
        at bndtools.central.Central.bndCall(Central.java:606)
        at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:127)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by bjhargrave** [comment]
Closing. Bndtools/Bnd has made the changes to avoid holding jars open. There are some bugs in other Eclipse plugins which are being worked.
